-- CPU
CREATE TABLE SYS_MGR.SYS_CPU
(
    DATE_TIME TIMESTAMP     NOT NULL,
    HOST_NAME VARCHAR(255) NOT NULL,
    SYS       NUMERIC(19, 0),
    IDLE      NUMERIC(19, 0),
    USR       NUMERIC(19, 0),
    WAIT      NUMERIC(19, 0),
    TOTAL     NUMERIC(19, 0),
    CONSTRAINT PK_SYS_CPU PRIMARY KEY (DATE_TIME, HOST_NAME)
);

-- MEMORY
CREATE TABLE SYS_MGR.SYS_MEM
(
    DATE_TIME   TIMESTAMP     NOT NULL,
    HOST_NAME   VARCHAR(255) NOT NULL,
    USED        NUMERIC(19, 0),
    FREE        NUMERIC(19, 0),
    ACTUAL_FREE NUMERIC(19, 0),
    ACTUAL_USED NUMERIC(19, 0),
    TOTAL       NUMERIC(19, 0),
    CONSTRAINT PK_SYS_MEM PRIMARY KEY (DATE_TIME, HOST_NAME)
);

-- SWAP
CREATE TABLE SYS_MGR.SYS_SWAP
(
    DATE_TIME   TIMESTAMP     NOT NULL,
    HOST_NAME   VARCHAR(255) NOT NULL,
    USED        NUMERIC(19, 0),
    FREE        NUMERIC(19, 0),
    TOTAL       NUMERIC(19, 0),
    CONSTRAINT PK_SYS_SWAP PRIMARY KEY (DATE_TIME, HOST_NAME)
);

-- DISK
CREATE TABLE SYS_MGR.SYS_DISK
(
    DATE_TIME        TIMESTAMP     NOT NULL,
    HOST_NAME        VARCHAR(255) NOT NULL,
    DISK_NAME        VARCHAR(255) NOT NULL,
    QUEUE            FLOAT,
    READ_LIVE_BYTES  NUMERIC(19, 0),
    READ_S           NUMERIC(19, 0),
    SERVICE_TIME     NUMERIC(19, 0),
    WRITE_LIVE_BYTES NUMERIC(19, 0),
    WRITES           NUMERIC(19, 0),
    TOTAL_BYTES      NUMERIC(19, 0),
    FREE_BYTES       NUMERIC(19, 0),
    USED_BYTES       NUMERIC(19, 0),
    USED_PERCENT     FLOAT,
    CONSTRAINT PK_SYS_DISK PRIMARY KEY (DATE_TIME, HOST_NAME, DISK_NAME)
);

-- EXCEPTION
CREATE TABLE SYS_MGR.SYS_EXCEPTION
(
    ID              NUMERIC(10, 0) NOT NULL,
    DATE_TIME       TIMESTAMP,
    CLASS_NAME      VARCHAR(255),
    EXCEPTION_CLASS VARCHAR(255),
    MESSAGE         VARCHAR(255),
    METHOD_NAME     VARCHAR(255),
    CONSTRAINT PK_SYS_EXCEPTION PRIMARY KEY (ID)
);

-- PROCESS
CREATE TABLE SYS_MGR.SYS_PROCESS
(
    DATE_TIME       TIMESTAMP       NOT NULL,
    HOST_NAME       VARCHAR(255)   NOT NULL,
    ARGS            VARCHAR(255),
    CPU_USAGE       FLOAT,
    DNAME           VARCHAR(255),
    MEMORY_USAGE    FLOAT,
    MEMORY_USAGE_MB NUMERIC(19, 0),
    PID             NUMERIC(19, 0) NOT NULL,
    PPID            NUMERIC(19, 0),
    PRIORITY        NUMERIC(10, 0),
    PROCESS_NAME    VARCHAR(255),
    STATE           CHAR(1),
    THREADS         NUMERIC(19, 0),
    CONSTRAINT PK_SYS_PROCESS PRIMARY KEY (DATE_TIME, HOST_NAME, PID)
);